# Generated by Django 5.1.7 on 2025-03-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_repo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
