# Generated by Django 5.1.7 on 2025-03-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_repo', '0002_remove_student_password_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=100),
        ),
    ]
