# Generated by Django 5.1.7 on 2025-03-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_repo', '0002_auto_20250320_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
