# Generated by Django 5.1.7 on 2025-03-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_repo', '0004_student_branch_student_gender_student_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('teacher_id', models.CharField(max_length=50, unique=True)),
                ('id_card', models.ImageField(upload_to='teacher_id_cards/')),
            ],
        ),
    ]
