# Generated by Django 5.1.7 on 2025-03-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_repo', '0005_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='letter_of_intent',
            field=models.FileField(blank=True, null=True, upload_to='teacher_documents/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='branch',
            field=models.CharField(default='Computer Science', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Female', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='teacher_id_cards/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
