# Generated by Django 5.1.7 on 2025-03-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_repo', '0007_alter_teacher_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/'),
        ),
    ]
