# Generated by Django 5.1.7 on 2025-03-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_repo', '0008_alter_teacher_id_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id_file',
            field=models.FileField(blank=True, null=True, upload_to='student_ids/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=' TEMP1233', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
