# Generated by Django 5.1.7 on 2025-03-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_repo', '0011_remove_teacher_letter_of_intent_student_reset_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
